
### get trips
GET http://127.0.0.1:3000/api/services
content-type: application/json

### get trips
GET http://127.0.0.1:3000/api/services/search?nombre=ped
content-type: application/json


### get trips
GET http://127.0.0.1:3000/api/personal
content-type: application/json

### get trips
GET http://127.0.0.1:3000/api/total-mes/6
content-type: application/json


### get trips
GET http://127.0.0.1:3000/api/servicios/categorias
content-type: application/json

### get trips
GET http://127.0.0.1:3000/api/servicios/Manos
content-type: application/json

### get trips
GET http://127.0.0.1:3000/api/services/664245bfe5f2b8152694866d
content-type: application/json

### get trips
GET http://127.0.0.1:3000/api/getAllCitas
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQyNDE0ODI2OWRmOGVjZmJiNmYzN2UiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTcwMjg0MjksImV4cCI6MTcxNzA1NzIyOX0.knJ-RxPYX5GEqwHHivnJc7WcRDoE1bhJJ-xlffIXHTk

###Completar
PUT http://127.0.0.1:3000/api/citas/6642a210dad9405091e6c94e/completar
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQyNDE0ODI2OWRmOGVjZmJiNmYzN2UiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTc2MjM2MjgsImV4cCI6MTcxNzY1MjQyOH0.Ieah8Sq7s2klgrFfIonwRBKhkXUcIpFSUl3S6caoNsw

{
    "total": 30,
    "atendidoPorId": "665e4179cb3ed01f11b4bf8a"
}


### get trips
GET http://127.0.0.1:3000/api/disponibilidad/6653c460dc52b042dea0f6f2/2024-06-06
content-type: application/json

### get reservation by date
GET http://127.0.0.1:3000/api/getSalesDataByMonth?month=4&year=2024
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQyNDE0ODI2OWRmOGVjZmJiNmYzN2UiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTY5MzY0ODUsImV4cCI6MTcxNjk2NTI4NX0.hpo4Am2r2eOATE4j2Nf7c2MB-5_sgypOK9iKB0PqkKQ

### get reservation by date
GET http://127.0.0.1:3000/api/reservations/count/2024/4
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWQ2MjRkZjE1MTBlNWUyNTRiNmRmZjUiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTI2MjU3MjgsImV4cCI6MTcxMjY1NDUyOH0.FBR1hIX829EHr9E2T7TKbWuXRmYNuP9-BnB252YupW0
###
GET https://nativo503sv.com/getReservationAuth.php

{
    "id":"661035cc38f977e3347d9d74"
}

### register user
GET http://127.0.0.1:3000/api/trips/topSelling
content-type: application/json


### register user
GET http://127.0.0.1:3000/api/reservations/nationalityHeatmap
content-type: application/json

### register user
POST http://127.0.0.1:3000/api/register
content-type: application/json

{
    "nombre": "Priscila Garcia",
    "username": "jadepris",
    "password": "jpris03$$",
    "roles" : ["Admin","Gerente"]
}

### login
POST http://127.0.0.1:3000/api/login
content-type: application/json

{
    "username": "alejandro",
    "password": "jlopez04$$"
}

### post trip
POST http://127.0.0.1:3000/api/services
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQyNDE0ODI2OWRmOGVjZmJiNmYzN2UiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTU2MTg5MjYsImV4cCI6MTcxNTY0NzcyNn0.bjLnuYDMe7wvO8PpM8b8sB1QAYJ1WKSy1cOOqAg6BuQ

{
    "images": [
        "https://phantom-elmundo.unidadeditorial.es/29a70c0f692ffe32a7bdd0707c7007c9/crop/463x204/2639x1836/resize/1280/f/webp/assets/multimedia/imagenes/2023/01/24/16745628932796.jpg"
        ],
    "nombre": "Manicura",
    "descripcion": "Manicura Especializada con nuestros mejores productos",
    "precio": {
        "min": "25",
        "max": "40" 
    },
    "indicaciones": "Manos limpias, sin colores",
    "duration": "30",
    "horarioInicio": "8:00",
    "horarioFin" : "17:00",
    "categoria" : "Manos"
}


### post trip
POST http://127.0.0.1:3000/api/postCita
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQyNDE0ODI2OWRmOGVjZmJiNmYzN2UiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTU2MTg5MjYsImV4cCI6MTcxNTY0NzcyNn0.bjLnuYDMe7wvO8PpM8b8sB1QAYJ1WKSy1cOOqAg6BuQ

{
    "servicioId": "664245bfe5f2b8152694866d",
    "nombre": "Priscila Lopez",
    "fechaNacimiento": "2001-08-23",
    "telefono": "75682298",
    "preferencias": "Me gusta mucho cuidarme el cabello ya que tiene mucho volumen y me encanta andar bella",
    "citaDate" : "2024-06-23",
    "hora": "13:00"
}
### post experiences
POST http://127.0.0.1:3000/api/insertUrls
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWQ2MjRkZjE1MTBlNWUyNTRiNmRmZjUiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTAzNzIwNjcsImV4cCI6MTcxMDQwMDg2N30.GCkggcVD-eqTqTvGKwA7P5yj1Hc4kKKAhs_3QG8XMo4

{
    "urls": [
      "https://nativo503sv.com/siteImages/IMG_1182.JPG",
      "https://nativo503sv.com/siteImages/IMG_1189.JPG",
      "https://nativo503sv.com/siteImages/IMG_0043.JPG",
      "https://nativo503sv.com/siteImages/IMG_0392.JPG"
    ]
}


### post car
POST http://127.0.0.1:3000/api/rentacars
content-type: application/json

{
    "brand": "Toyota",
    "model":"Rav4",
    "year": 2019,
    "pricePerDay": 25.00,
    "images": [
        "https://nativo503sv.com/siteImages/toyota1.jpg",
        "https://nativo503sv.com/siteImages/toyota1.jpg"
      ]
}

### post car
POST http://127.0.0.1:3000/api/rentacars/65f3b3c92c506de6c4226608/reserve
content-type: application/json

{

    "startDate": "2024-03-17",
    "endDate":"2024-03-21",
    "totalCost": 100
    
}

#65f3b3c92c506de6c4226608


### get salesbyMonth
GET http://127.0.0.1:3000/api/getAllReservations
content-type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWQ2MjRkZjE1MTBlNWUyNTRiNmRmZjUiLCJ1c2VybmFtZSI6ImFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluIiwiVXNlciJdLCJpYXQiOjE3MTA0NzEzNTcsImV4cCI6MTcxMDUwMDE1N30.hSAcj1o586C1eG28POs438YGbFwc12_IskIycrChsrE


### get rentacars
GET https://whale-app-xddlc.ondigitalocean.app/api/rentacars
content-type: application/json

### get reservationsRentacar
GET http://127.0.0.1:3000/api/rentacars/65fa52e70e6915a90d144dca/reservations
content-type: application/json

### get reservationsRentacar
GET http://127.0.0.1:3000/api/rentacars/65fa52e70e6915a90d144dca/reservationsAll
content-type: application/json

###
GET http://127.0.0.1:3000/api/random-reviews
content-type: application/json



### post reservation
POST https://whale-app-xddlc.ondigitalocean.app/api/postReservation
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA1MzE5MTQsImV4cCI6MTcwMTEzNjcxNCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.qQ036SH8-73JFNcTJRf953b3y_xYX9wUMxNk1PxPVSE

{
    "tripId": "65b44d3021464162c6893f44",
    "fullName":"Javier Alejandro Lopez",
    "email": "lopez.javier0412@gmail.com",
    "customersQty":1,
    "total":125,
    "phoneNumber": "+50375682298",
    "idNumber":"04731187-4",
    "pickupAddress": "Calle Gerardo Barrios, Av. Bolivar, La Libertad",
    "reservationDate": "05-23-2024",
    "preferedLanguage": "Spanish",
    "originNation": "El Salvador",
    "deseaseOrmedicine": "No"
}

### update reservation
PUT http://localhost:3000/api/services/664819d758bd0b30d94806f0
content-type: application/json

{
    "horarioInicio" : "8:30",
    "horarioFin" : "17:30"
    
}



### post reservation
POST https://nativo503sv.com/updateReservation.php
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA1MzE5MTQsImV4cCI6MTcwMTEzNjcxNCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.qQ036SH8-73JFNcTJRf953b3y_xYX9wUMxNk1PxPVSE

{"SatisFactorio":true,
"Codigo":"00",
"Mensaje":"AUTORIZADO",
"Fecha":"2024-03-18T11:39:25.586216-06:00",
"NumeroAutorizacion":"093468",
"ClientIdTransaction":"661cac0c07dd72b972d3bc9d",
"OrdenCompra":null,
"MaskPan":"999999****5848",
"CardHolder":"Javier Lopez",
"Documento":null,
"MedioPago":"COMPRA",
"NumeroReferencia":"407811000004",
"SecretToken":null,
"IsCloseView":true,
"MontoNeto":"115",
"Monto":"115",
"Puntos":null,
"IsRedirect":true,
"UrlRedirect":"http://nativo503sv.com/",
"Referencia":"407811000004",
"TransaccionId":"61557",
"Email":null,
"Direccion":null,
"Telefono":null,
"Cantidad":null,
"Total":null,
"StringBtc":null,
"Aranceles":null,
"TokenComercio":null,
"Adicionales":"Cobro por reservacion",
"MontoCuota":0.0
}


### post reservation
POST http://127.0.0.1:3000/api/postReview
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA1MzE5MTQsImV4cCI6MTcwMTEzNjcxNCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.qQ036SH8-73JFNcTJRf953b3y_xYX9wUMxNk1PxPVSE

{
    "tripId": "65b44d3021464162c6893f44",
    "commentary": "Una de las mejores experiencias en la vida",
    "stars": 4,
    "name": "Javier Lopez"
}

####

WEBDEVJUNKIE
CODINGWITHBASIR

### editar
PUT http://127.0.0.1:5000/pacientes/editar
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDAxMDMyNTQsImV4cCI6MTcwMDEwNjg1NCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.NBT7oataCzaN-Ye_VzpzCWpuGCRcguJCO3qHW81__1E

{
    "images": [
        "https://elsalvador.travel/system/wp-content/uploads/2020/01/Mural-de-Ataco2.jpg",
        "https://elsalvador.travel/system/wp-content/uploads/2020/01/Mural-de-Ataco2.jpg"
        ],
    "destTitle":"Ataco",
    "location":"Sonsonate, El Salvador",
    "category":"Colonial Town",
    "price": 70,
    "description":"One of the colonial town in Ruta de las flores, this is an important town for tourism.",
    "include": [
        "Transportation",
        "Hostel",
        "Guide",
        "Walk around the town"
        ]
}

### editar
PUT http://127.0.0.1:3000/api/updateCommentary/65b44d3021464162c6893f44
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDAxMDMyNTQsImV4cCI6MTcwMDEwNjg1NCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.NBT7oataCzaN-Ye_VzpzCWpuGCRcguJCO3qHW81__1E

{
    "commentary" : "Uno de los mejores trips, te pone a prueba la subida pero la pasas genial y la vista es increible",
    "stars" : 4,
    "name" : "Cristian Martinez"
}

### borrar pacientes
DELETE  http://127.0.0.1:5000/pacientes/borrar/16781
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA1MzE5MTQsImV4cCI6MTcwMTEzNjcxNCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.qQ036SH8-73JFNcTJRf953b3y_xYX9wUMxNk1PxPVSE
